title: Eamon Wong
logo: assets/EamonWongHeadShot.jpg
description: |
  I am a software developer with expertise in Python, Flask, and Django, and experience in rapid development, debugging, and testing at Planck. My freelance projects, such as a content aggregator and expense tracker, have further honed my technical skills. I have completed Harvard's CS50 and freeCodeCamp's Python Certification, deepening my knowledge of data structures, algorithms, and Python. I excel in communication and teamwork, mentoring interns, and collaborating with senior developers, and I bring agility and innovation from my startup experience.
theme: jekyll-theme-minimal

