title: Eamon Wong
logo: assets/EamonWongHeadShot.jpg
description: |
  Dedicated and enthusiastic Software Developer seeking a role to apply exceptional ability to switch between programming languages and frameworks as needed, while working quickly and independently.
theme: jekyll-theme-minimal

